# -*- coding: utf-8 -*-
"""
EcoSphere AI — ESG Reports Model
Defines configurations for standard and custom reports.
"""

from odoo import fields, models


class ESGReport(models.Model):
    """
    Standard and custom report generator specifications.
    """
    _name = 'ecosphere.report'
    _description = 'ESG Report Template & Config'
    _order = 'create_date desc'

    name = fields.Char(string='Report Name', required=True)
    report_type = fields.Selection([
        ('environmental', 'Environmental Report'),
        ('social', 'Social Report'),
        ('governance', 'Governance Report'),
        ('esg_summary', 'ESG Summary Report'),
        ('department', 'Department Performance Report'),
        ('employee', 'Employee ESG Contribution Report'),
        ('challenge', 'Challenge Participation & Impact Report'),
        ('custom', 'Custom Report Builder'),
    ], string='Report Type', required=True, default='esg_summary')

    period_start = fields.Date(string='Period Start')
    period_end = fields.Date(string='Period End')
    department_ids = fields.Many2many('hr.department', string='Departments')
    employee_ids = fields.Many2many('hr.employee', string='Employees')

    format = fields.Selection([
        ('pdf', 'PDF Report'),
        ('excel', 'Excel (XLSX)'),
        ('csv', 'CSV'),
        ('json', 'JSON'),
    ], string='Export Format', default='pdf', required=True)

    generated_by = fields.Many2one('res.users', string='Generated By', default=lambda self: self.env.user)
    generated_file = fields.Binary(string='Generated Document', attachment=True)
    file_name = fields.Char(string='File Name')
    notes = fields.Text(string='Notes / Summary')
